// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "github.com/atombender/go-jsonschema/pkg/types"
import "time"

// The document an adapter writes to --out: the run envelope plus the derived facts
// (and any provisional entities/aliases). envelope.resultHash is the SHA-256 over
// RFC 8785 (JCS) canonical JSON of the facts, sorted by factHash — deterministic
// across runs.
type AdapterOutput struct {
	// Entities corresponds to the JSON schema field "entities".
	Entities []Entity `json:"entities,omitempty,omitzero" yaml:"entities,omitempty" mapstructure:"entities,omitempty"`

	// EntityAliases corresponds to the JSON schema field "entityAliases".
	EntityAliases []EntityAlias `json:"entityAliases,omitempty,omitzero" yaml:"entityAliases,omitempty" mapstructure:"entityAliases,omitempty"`

	// Envelope corresponds to the JSON schema field "envelope".
	Envelope IngestionEnvelope `json:"envelope" yaml:"envelope" mapstructure:"envelope"`

	// Facts corresponds to the JSON schema field "facts".
	Facts []FiscalFact `json:"facts" yaml:"facts" mapstructure:"facts"`
}

type AssignedBy string

const AssignedByHuman AssignedBy = "human"
const AssignedByModel AssignedBy = "model"
const AssignedByRule AssignedBy = "rule"
const AssignedBySource AssignedBy = "source"

type ClassificationAssignment struct {
	// AssignedBy corresponds to the JSON schema field "assignedBy".
	AssignedBy AssignedBy `json:"assignedBy" yaml:"assignedBy" mapstructure:"assignedBy"`

	// AssignmentId corresponds to the JSON schema field "assignmentId".
	AssignmentId *Uuid `json:"assignmentId,omitempty,omitzero" yaml:"assignmentId,omitempty" mapstructure:"assignmentId,omitempty"`

	// Basis corresponds to the JSON schema field "basis".
	Basis *string `json:"basis,omitempty,omitzero" yaml:"basis,omitempty" mapstructure:"basis,omitempty"`

	// Code corresponds to the JSON schema field "code".
	Code string `json:"code" yaml:"code" mapstructure:"code"`

	// Confidence corresponds to the JSON schema field "confidence".
	Confidence *float64 `json:"confidence,omitempty,omitzero" yaml:"confidence,omitempty" mapstructure:"confidence,omitempty"`

	// FactId corresponds to the JSON schema field "factId".
	FactId *Uuid `json:"factId,omitempty,omitzero" yaml:"factId,omitempty" mapstructure:"factId,omitempty"`

	// SchemeId corresponds to the JSON schema field "schemeId".
	SchemeId SchemeId `json:"schemeId" yaml:"schemeId" mapstructure:"schemeId"`

	// Version corresponds to the JSON schema field "version".
	Version int `json:"version" yaml:"version" mapstructure:"version"`
}

type ControlTotal struct {
	// DerivationQuery corresponds to the JSON schema field "derivationQuery".
	DerivationQuery string `json:"derivationQuery" yaml:"derivationQuery" mapstructure:"derivationQuery"`

	// FiscalYear corresponds to the JSON schema field "fiscalYear".
	FiscalYear FiscalYear `json:"fiscalYear" yaml:"fiscalYear" mapstructure:"fiscalYear"`

	// Flow corresponds to the JSON schema field "flow".
	Flow Flow `json:"flow" yaml:"flow" mapstructure:"flow"`

	// Jurisdiction corresponds to the JSON schema field "jurisdiction".
	Jurisdiction string `json:"jurisdiction" yaml:"jurisdiction" mapstructure:"jurisdiction"`

	// OfficialTotal corresponds to the JSON schema field "officialTotal".
	OfficialTotal Money `json:"officialTotal" yaml:"officialTotal" mapstructure:"officialTotal"`

	// RawSha256 corresponds to the JSON schema field "rawSha256".
	RawSha256 Sha256 `json:"rawSha256" yaml:"rawSha256" mapstructure:"rawSha256"`
}

type Entity struct {
	// CanonicalName corresponds to the JSON schema field "canonicalName".
	CanonicalName string `json:"canonicalName" yaml:"canonicalName" mapstructure:"canonicalName"`

	// Ein corresponds to the JSON schema field "ein".
	Ein *string `json:"ein,omitempty,omitzero" yaml:"ein,omitempty" mapstructure:"ein,omitempty"`

	// EntityId corresponds to the JSON schema field "entityId".
	EntityId *Uuid `json:"entityId,omitempty,omitzero" yaml:"entityId,omitempty" mapstructure:"entityId,omitempty"`

	// Jurisdiction corresponds to the JSON schema field "jurisdiction".
	Jurisdiction *string `json:"jurisdiction,omitempty,omitzero" yaml:"jurisdiction,omitempty" mapstructure:"jurisdiction,omitempty"`

	// Kind corresponds to the JSON schema field "kind".
	Kind EntityKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Uei corresponds to the JSON schema field "uei".
	Uei *string `json:"uei,omitempty,omitzero" yaml:"uei,omitempty" mapstructure:"uei,omitempty"`
}

type EntityAlias struct {
	// AliasId corresponds to the JSON schema field "aliasId".
	AliasId *Uuid `json:"aliasId,omitempty,omitzero" yaml:"aliasId,omitempty" mapstructure:"aliasId,omitempty"`

	// Confidence corresponds to the JSON schema field "confidence".
	Confidence *float64 `json:"confidence,omitempty,omitzero" yaml:"confidence,omitempty" mapstructure:"confidence,omitempty"`

	// EntityId corresponds to the JSON schema field "entityId".
	EntityId *Uuid `json:"entityId,omitempty,omitzero" yaml:"entityId,omitempty" mapstructure:"entityId,omitempty"`

	// MatchedBy corresponds to the JSON schema field "matchedBy".
	MatchedBy EntityAliasMatchedBy `json:"matchedBy" yaml:"matchedBy" mapstructure:"matchedBy"`

	// NameRaw corresponds to the JSON schema field "nameRaw".
	NameRaw string `json:"nameRaw" yaml:"nameRaw" mapstructure:"nameRaw"`

	// Source corresponds to the JSON schema field "source".
	Source EntityAliasSource `json:"source" yaml:"source" mapstructure:"source"`
}

type EntityAliasMatchedBy string

const EntityAliasMatchedByHuman EntityAliasMatchedBy = "human"
const EntityAliasMatchedByIdentifier EntityAliasMatchedBy = "identifier"
const EntityAliasMatchedByModel EntityAliasMatchedBy = "model"
const EntityAliasMatchedByRule EntityAliasMatchedBy = "rule"

type EntityAliasSource map[string]interface{}

type EntityKind string

const EntityKindGovernment EntityKind = "government"
const EntityKindIndividual EntityKind = "individual"
const EntityKindNonprofit EntityKind = "nonprofit"
const EntityKindUnknown EntityKind = "unknown"
const EntityKindVendor EntityKind = "vendor"

// The atom. Mirrors fiscal_fact. Provenance required (Hard Rule 1):
// derivationQuery always; rawSha256 for transaction/award grain. amount is a
// decimal string (Hard Rule 2).
type FiscalFact struct {
	// Amount corresponds to the JSON schema field "amount".
	Amount Money `json:"amount" yaml:"amount" mapstructure:"amount"`

	// Assignments corresponds to the JSON schema field "assignments".
	Assignments []ClassificationAssignment `json:"assignments,omitempty,omitzero" yaml:"assignments,omitempty" mapstructure:"assignments,omitempty"`

	// Currency corresponds to the JSON schema field "currency".
	Currency Iso4217 `json:"currency" yaml:"currency" mapstructure:"currency"`

	// DerivationQuery corresponds to the JSON schema field "derivationQuery".
	DerivationQuery string `json:"derivationQuery" yaml:"derivationQuery" mapstructure:"derivationQuery"`

	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty,omitzero" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// FactHash corresponds to the JSON schema field "factHash".
	FactHash Sha256 `json:"factHash" yaml:"factHash" mapstructure:"factHash"`

	// FactId corresponds to the JSON schema field "factId".
	FactId *Uuid `json:"factId,omitempty,omitzero" yaml:"factId,omitempty" mapstructure:"factId,omitempty"`

	// FiscalYear corresponds to the JSON schema field "fiscalYear".
	FiscalYear FiscalYear `json:"fiscalYear" yaml:"fiscalYear" mapstructure:"fiscalYear"`

	// Flow corresponds to the JSON schema field "flow".
	Flow Flow `json:"flow" yaml:"flow" mapstructure:"flow"`

	// Grain corresponds to the JSON schema field "grain".
	Grain Grain `json:"grain" yaml:"grain" mapstructure:"grain"`

	// Jurisdiction corresponds to the JSON schema field "jurisdiction".
	Jurisdiction string `json:"jurisdiction" yaml:"jurisdiction" mapstructure:"jurisdiction"`

	// OccurredOn corresponds to the JSON schema field "occurredOn".
	OccurredOn *types.SerializableDate `json:"occurredOn,omitempty,omitzero" yaml:"occurredOn,omitempty" mapstructure:"occurredOn,omitempty"`

	// PayeeEntity corresponds to the JSON schema field "payeeEntity".
	PayeeEntity *Uuid `json:"payeeEntity,omitempty,omitzero" yaml:"payeeEntity,omitempty" mapstructure:"payeeEntity,omitempty"`

	// PayerEntity corresponds to the JSON schema field "payerEntity".
	PayerEntity *Uuid `json:"payerEntity,omitempty,omitzero" yaml:"payerEntity,omitempty" mapstructure:"payerEntity,omitempty"`

	// RawSha256 corresponds to the JSON schema field "rawSha256".
	RawSha256 *Sha256 `json:"rawSha256,omitempty,omitzero" yaml:"rawSha256,omitempty" mapstructure:"rawSha256,omitempty"`

	// RunId corresponds to the JSON schema field "runId".
	RunId *Uuid `json:"runId,omitempty,omitzero" yaml:"runId,omitempty" mapstructure:"runId,omitempty"`

	// Supersedes corresponds to the JSON schema field "supersedes".
	Supersedes *Uuid `json:"supersedes,omitempty,omitzero" yaml:"supersedes,omitempty" mapstructure:"supersedes,omitempty"`
}

// One row of a computed view: a scheme code (or entity id, or __unclassified__)
// with its rolled-up amount (API payload only, NOT storage). The scheme is carried
// once on the enclosing FiscalYearView.
type FiscalNodeView struct {
	// Amount corresponds to the JSON schema field "amount".
	Amount Money `json:"amount" yaml:"amount" mapstructure:"amount"`

	// Code corresponds to the JSON schema field "code".
	Code string `json:"code" yaml:"code" mapstructure:"code"`

	// Currency corresponds to the JSON schema field "currency".
	Currency Iso4217 `json:"currency" yaml:"currency" mapstructure:"currency"`

	// FactCount corresponds to the JSON schema field "factCount".
	FactCount int `json:"factCount" yaml:"factCount" mapstructure:"factCount"`

	// Label corresponds to the JSON schema field "label".
	Label string `json:"label" yaml:"label" mapstructure:"label"`
}

// Canonical cross-language contract for Outlays. Single source of truth; language
// types are generated from this file. Wire format is camelCase; storage (DDL) is
// snake_case. See ARCHITECTURE.md Sections 3-5.
type FiscalSchemaJson map[string]interface{}

// Fiscal year token (Hard Rule 8): YYYY or YYYY-YY.
type FiscalYear string

// A one-level jurisdiction-year rollup over one scheme/flow (API payload only, NOT
// storage). unmapped is the total of facts with no assignment in the scheme, also
// surfaced as the __unclassified__ node — node amounts always reconcile to total
// (D24).
type FiscalYearView struct {
	// Currency corresponds to the JSON schema field "currency".
	Currency Iso4217 `json:"currency" yaml:"currency" mapstructure:"currency"`

	// FiscalYear corresponds to the JSON schema field "fiscalYear".
	FiscalYear FiscalYear `json:"fiscalYear" yaml:"fiscalYear" mapstructure:"fiscalYear"`

	// Flow corresponds to the JSON schema field "flow".
	Flow Flow `json:"flow" yaml:"flow" mapstructure:"flow"`

	// Jurisdiction corresponds to the JSON schema field "jurisdiction".
	Jurisdiction string `json:"jurisdiction" yaml:"jurisdiction" mapstructure:"jurisdiction"`

	// Nodes corresponds to the JSON schema field "nodes".
	Nodes []FiscalNodeView `json:"nodes" yaml:"nodes" mapstructure:"nodes"`

	// SchemeId corresponds to the JSON schema field "schemeId".
	SchemeId string `json:"schemeId" yaml:"schemeId" mapstructure:"schemeId"`

	// Total corresponds to the JSON schema field "total".
	Total Money `json:"total" yaml:"total" mapstructure:"total"`

	// Unmapped corresponds to the JSON schema field "unmapped".
	Unmapped Money `json:"unmapped" yaml:"unmapped" mapstructure:"unmapped"`
}

type Flow string

const FlowRevenue Flow = "revenue"
const FlowSpending Flow = "spending"

type Grain string

const GrainAggregate Grain = "aggregate"
const GrainAward Grain = "award"
const GrainTransaction Grain = "transaction"

// Result of one adapter run. signature/signerKeyId are present now (null) so
// Phase-2 federated signed submissions need no schema rework (Decision D6).
type IngestionEnvelope struct {
	// AdapterId corresponds to the JSON schema field "adapterId".
	AdapterId string `json:"adapterId" yaml:"adapterId" mapstructure:"adapterId"`

	// AdapterVersion corresponds to the JSON schema field "adapterVersion".
	AdapterVersion string `json:"adapterVersion" yaml:"adapterVersion" mapstructure:"adapterVersion"`

	// EnvelopeVersion corresponds to the JSON schema field "envelopeVersion".
	EnvelopeVersion interface{} `json:"envelopeVersion" yaml:"envelopeVersion" mapstructure:"envelopeVersion"`

	// FetchedAt corresponds to the JSON schema field "fetchedAt".
	FetchedAt time.Time `json:"fetchedAt" yaml:"fetchedAt" mapstructure:"fetchedAt"`

	// FiscalYear corresponds to the JSON schema field "fiscalYear".
	FiscalYear FiscalYear `json:"fiscalYear" yaml:"fiscalYear" mapstructure:"fiscalYear"`

	// Jurisdiction corresponds to the JSON schema field "jurisdiction".
	Jurisdiction string `json:"jurisdiction" yaml:"jurisdiction" mapstructure:"jurisdiction"`

	// RawSnapshots corresponds to the JSON schema field "rawSnapshots".
	RawSnapshots []RawSnapshotRef `json:"rawSnapshots" yaml:"rawSnapshots" mapstructure:"rawSnapshots"`

	// ResultHash corresponds to the JSON schema field "resultHash".
	ResultHash Sha256 `json:"resultHash" yaml:"resultHash" mapstructure:"resultHash"`

	// RunId corresponds to the JSON schema field "runId".
	RunId Uuid `json:"runId" yaml:"runId" mapstructure:"runId"`

	// Signature corresponds to the JSON schema field "signature".
	Signature IngestionEnvelopeSignature `json:"signature" yaml:"signature" mapstructure:"signature"`

	// SignerKeyId corresponds to the JSON schema field "signerKeyId".
	SignerKeyId IngestionEnvelopeSignerKeyId `json:"signerKeyId" yaml:"signerKeyId" mapstructure:"signerKeyId"`
}

type IngestionEnvelopeSignature *string

type IngestionEnvelopeSignerKeyId *string

// ISO 4217 currency code.
type Iso4217 string

// Monetary amount as a decimal string. JS number / floats forbidden (Hard Rule 2).
type Money string

type RawSnapshotRef struct {
	// Bytes corresponds to the JSON schema field "bytes".
	Bytes int `json:"bytes" yaml:"bytes" mapstructure:"bytes"`

	// HttpStatus corresponds to the JSON schema field "httpStatus".
	HttpStatus int `json:"httpStatus" yaml:"httpStatus" mapstructure:"httpStatus"`

	// Sha256 corresponds to the JSON schema field "sha256".
	Sha256 Sha256 `json:"sha256" yaml:"sha256" mapstructure:"sha256"`

	// Url corresponds to the JSON schema field "url".
	Url string `json:"url" yaml:"url" mapstructure:"url"`
}

type SchemeId string

const SchemeIdCofog SchemeId = "cofog"
const SchemeIdDepartment SchemeId = "department"
const SchemeIdFund SchemeId = "fund"
const SchemeIdObjectClass SchemeId = "object_class"
const SchemeIdProgram SchemeId = "program"
const SchemeIdRecipientType SchemeId = "recipient_type"
const SchemeIdTag SchemeId = "tag"
const SchemeIdUsCaAcquisitionType SchemeId = "us_ca_acquisition_type"
const SchemeIdUsCaDepartment SchemeId = "us_ca_department"

// Lowercase hex SHA-256 digest.
type Sha256 string

type SourceRef struct {
	// Dataset corresponds to the JSON schema field "dataset".
	Dataset string `json:"dataset" yaml:"dataset" mapstructure:"dataset"`

	// DerivationQuery corresponds to the JSON schema field "derivationQuery".
	DerivationQuery string `json:"derivationQuery" yaml:"derivationQuery" mapstructure:"derivationQuery"`

	// Jurisdiction corresponds to the JSON schema field "jurisdiction".
	Jurisdiction string `json:"jurisdiction" yaml:"jurisdiction" mapstructure:"jurisdiction"`

	// PulledAt corresponds to the JSON schema field "pulledAt".
	PulledAt time.Time `json:"pulledAt" yaml:"pulledAt" mapstructure:"pulledAt"`

	// RawSha256 corresponds to the JSON schema field "rawSha256".
	RawSha256 Sha256 `json:"rawSha256" yaml:"rawSha256" mapstructure:"rawSha256"`

	// ResourceId corresponds to the JSON schema field "resourceId".
	ResourceId string `json:"resourceId" yaml:"resourceId" mapstructure:"resourceId"`
}

type Uuid string
