# generated by datamodel-codegen:
#   filename:  fiscal.schema.json

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class OutlaysContract(BaseModel):
    pass


class Money(RootModel[str]):
    root: str = Field(
        ...,
        description="Monetary amount as a decimal string. JS number / floats forbidden (Hard Rule 2).",
        pattern="^-?\\d{1,18}(\\.\\d{1,4})?$",
        title="Money",
    )


class Iso4217(RootModel[str]):
    root: str = Field(
        ...,
        description="ISO 4217 currency code.",
        pattern="^[A-Z]{3}$",
        title="Iso4217",
    )


class FiscalYear(RootModel[str]):
    root: str = Field(
        ...,
        description="Fiscal year token (Hard Rule 8): YYYY or YYYY-YY.",
        pattern="^\\d{4}(-\\d{2})?$",
        title="FiscalYear",
    )


class Sha256(RootModel[str]):
    root: str = Field(
        ...,
        description="Lowercase hex SHA-256 digest.",
        pattern="^[a-f0-9]{64}$",
        title="Sha256",
    )


class Uuid(RootModel[UUID]):
    root: UUID = Field(
        ...,
        pattern="^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$",
        title="Uuid",
    )


class Flow(Enum):
    revenue = "revenue"
    spending = "spending"


class Grain(Enum):
    transaction = "transaction"
    award = "award"
    aggregate = "aggregate"


class EntityKind(Enum):
    government = "government"
    vendor = "vendor"
    nonprofit = "nonprofit"
    individual = "individual"
    unknown = "unknown"


class AssignedBy(Enum):
    source = "source"
    rule = "rule"
    model = "model"
    human = "human"


class SchemeId(Enum):
    cofog = "cofog"
    object_class = "object_class"
    department = "department"
    fund = "fund"
    program = "program"
    recipient_type = "recipient_type"
    tag = "tag"
    us_ca_department = "us_ca_department"
    us_ca_acquisition_type = "us_ca_acquisition_type"


class SourceRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    jurisdiction: str
    dataset: str
    resourceId: str
    derivationQuery: str
    pulledAt: AwareDatetime
    rawSha256: Sha256


class Entity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    entityId: Uuid | None = None
    kind: EntityKind
    canonicalName: str = Field(..., min_length=1)
    uei: str | None = None
    ein: str | None = None
    jurisdiction: str | None = None


class MatchedBy(Enum):
    identifier = "identifier"
    rule = "rule"
    model = "model"
    human = "human"


class EntityAlias(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    aliasId: Uuid | None = None
    entityId: Uuid | None = None
    nameRaw: str = Field(..., min_length=1)
    matchedBy: MatchedBy
    confidence: float | None = None
    source: dict[str, Any]


class ClassificationAssignment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    assignmentId: Uuid | None = None
    factId: Uuid | None = None
    schemeId: SchemeId
    code: str = Field(..., min_length=1)
    assignedBy: AssignedBy
    confidence: float | None = None
    basis: str | None = None
    version: int = Field(..., ge=1)


class FiscalFact(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    factId: Uuid | None = None
    runId: Uuid | None = None
    jurisdiction: str
    fiscalYear: FiscalYear
    flow: Flow
    grain: Grain
    payerEntity: Uuid | None = None
    payeeEntity: Uuid | None = None
    amount: Money
    currency: Iso4217
    occurredOn: date | None = None
    description: str | None = None
    rawSha256: Sha256 | None = None
    derivationQuery: str = Field(..., min_length=1)
    factHash: Sha256
    supersedes: Uuid | None = None
    assignments: list[ClassificationAssignment] | None = None


class ControlTotal(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    jurisdiction: str
    fiscalYear: FiscalYear
    flow: Flow
    officialTotal: Money
    rawSha256: Sha256
    derivationQuery: str = Field(..., min_length=1)


class RawSnapshotRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sha256: Sha256
    url: str
    bytes: int = Field(..., ge=0)
    httpStatus: int


class IngestionEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    envelopeVersion: Literal["1"]
    adapterId: str = Field(..., min_length=1)
    adapterVersion: str = Field(..., min_length=1)
    runId: Uuid
    fetchedAt: AwareDatetime
    rawSnapshots: list[RawSnapshotRef]
    jurisdiction: str
    fiscalYear: FiscalYear
    resultHash: Sha256
    signature: str | None
    signerKeyId: str | None


class AdapterOutput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    envelope: IngestionEnvelope
    facts: list[FiscalFact]
    entities: list[Entity] | None = None
    entityAliases: list[EntityAlias] | None = None


class FiscalNodeView(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: str
    label: str
    amount: Money
    currency: Iso4217
    factCount: int = Field(..., ge=0)


class FiscalYearView(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    jurisdiction: str
    fiscalYear: FiscalYear
    flow: Flow
    schemeId: str
    total: Money
    currency: Iso4217
    unmapped: Money
    nodes: list[FiscalNodeView]
